name: Merge-upstream

on:
  workflow_dispatch:
  push:
    branches: 
      - master
  schedule:
    - cron: 30 */2 * * *

jobs:
  merge:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master
        fetch-depth: 0
        lfs: true
        token: ${{ secrets.WORKFLOW_TOKEN }}

    - name: Set git identity
      run : |
        git config --global user.email "tofuliang@gmail.com"
        git config --global user.name "tofuliang"
    - name: rebase on upstream commits
      env:
        DOWNSTREAM_BRANCH: master
      run : |
        git remote add upstream https://github.com/aaa1115910/bv.git
        git fetch upstream
        if [ $(git diff upstream/master HEAD^ |wc -l) -gt 0 ];then
          cp .github/workflows/release.yml /tmp/release.yml
          git reset upstream/master
          git reset --hard upstream/master
          cp /tmp/release.yml .github/workflows/release.yml
          git add .github
          git clean -fd
          git commit -m "rebase"
          git push -f origin $DOWNSTREAM_BRANCH
        fi
        git checkout -b develop --track origin/develop
        if [ $(git diff upstream/develop HEAD^ |wc -l) -gt 0 ];then
          git reset upstream/develop
          git reset --hard upstream/develop
          git clean -fd
          git push -f origin develop
        fi
